//Leer
###
GET https://tarjeta.fly.dev/users/obtener HTTP/1.1

//Buscar
###
GET https://tarjeta.fly.dev/users/?id=1 HTTP/1.1

//Insertar
###
POST https://tarjeta.fly.dev/users/nuevo HTTP/1.1
Content-Type: application/json

{
"nombre":"Edilson",
"adress":"calle 13",
"phone":"9991997636",
"email":"chelito@gmail.com",
"website":"https://yairhernandezpech.github.io/Portafolio_YairHP/",
"logo":"https://cdn-icons-png.flaticon.com/512/1524/1524855.png",
"facebooklink":"https://www.facebook.com/yair.hernandez.712",
"twitterlink":"nullo",
"instagramlink":"https://www.instagram.com/yairhernandez52/",
"linkedinlink":"https://www.linkedin.com/in/yair-hernandez/",
"youtubelink":"https://www.youtube.com/@yairhernandez7960"

}

//Actualizar
###
PUT https://tarjeta.fly.dev/users/actualizar/2 HTTP/1.1
Content-Type: application/json

{

"nombre":"Yair",
"contraseña":"Yair022"

}

//Eliminar
### 
DELETE https://tarjeta.fly.dev/users/eliminar/4 HTTP/1.1
